### ISSUE TITLE
release as 0.2.0

### ISSUE THREAD

**Issue by doekenorg** [leblanc-simon/parsedown-checkbox#4]
Hi @leblanc-simon, 

Would you be willing to drop the `-beta` suffix from the latest version?
Reason for this is that we use your package in a project. That project is the base for a specific installation. While we can set the `minimum-stability` on the base-project to `dev` and the `prefere-stable` to `true`, but we cannot do this for the specific installation. 

This causes us to be unable to install your package in the specific installation, as it does not match the `minimum-stability`.

Maybe you have the `-beta`-tag to indicatie it isn't a stable release. But the fact that you're on a `0.y.z` version implies the same (at least according to semver). 

Our only other option is to clone this repo, and tag our own; but that seems silly :-) 

Hope this is a possibility.

**Comment by sjadema** [comment]
I would really like a stable release as well for our project!

**Comment by leblanc-simon** [comment]
Hi !
I will check this possibility sunday ☺

**Comment by leblanc-simon** [comment]
done :)

**Comment by doekenorg** [comment]
Awesome. Thank you so much.

**Comment by sjadema** [comment]
Thanks man!
